"""added status of post,and description of post

Revision ID: 190ebf30c20a
Revises: c826fbd364d7
Create Date: 2025-01-15 13:58:08.272969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190ebf30c20a'
down_revision = 'c826fbd364d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_description'), ['description'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_description'))
        batch_op.drop_column('status')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
