"""added conversation table

Revision ID: 90cb3e14f16d
Revises: 190ebf30c20a
Create Date: 2025-01-28 15:28:57.927763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90cb3e14f16d'
down_revision = '190ebf30c20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation', sa.String(length=5000), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_conversation'), ['conversation'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_conversation'))
        batch_op.drop_column('conversation')

    # ### end Alembic commands ###
